/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vdip5ap0LSO
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/AD_select"
import { Input } from "@/components/ui/AD_input"
import { Button } from "@/components/ui/AD_button"
import Link from "next/link"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/AD_dropdown-menu"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/AD_table"
import { Switch } from "@/components/ui/AD_switch"
import { SVGProps } from "react"
import "@/app/globals.css";

export default function Admin() {
  return (
    <div className="flex h-full max-h-screen flex-col gap-2">
      <div className="flex flex-col">
      
      <header className="flex items-center justify-between py-6 px-6 gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
        <a className="text-3xl font-bold mb-4 mt-4">취지직 관리자 페이지</a>
        <div className="flex space-x-4">
          <Button className="text-black bg-[#F1F5F9] hover:bg-[#D1D5D9]" variant="ghost">
            관리자님
          </Button>
          <Button className="text-black bg-[#F1F5F9] hover:bg-[#D1D5D9]" variant="ghost">
            <Link href="/privacy-policy">로그아웃</Link>
          </Button>
        </div>
      </header>
      <main className="flex flex-col gap-2 p-4 md:gap-8 md:p-6">
        <div className="flex items-center justify-end w-full">
          <div className="relative w-1/5">
            <Select defaultValue="seller">
              <SelectTrigger>
                <SelectValue>Role</SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="seller">Seller</SelectItem>
                <SelectItem value="buyer">Buyer</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

          <div className="border shadow-sm rounded-lg">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">이름</TableHead>
                  <TableHead className="hidden md:table-cell">아이디</TableHead>
                  <TableHead className="min-w-[150px]">전화번호</TableHead>
                  <TableHead className="hidden md:table-cell">상태</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="flex items-center">
                    <span className="ml-2 font-medium">박수진</span>
                  </TableCell>
                  <TableCell className="font-medium">abc123</TableCell>
                  <TableCell className="hidden md:table-cell">01094285432</TableCell>
                  <TableCell className="hidden md:table-cell">
                    <Switch className="mx-auto" defaultChecked />
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="flex items-center">
                    <span className="ml-2 font-medium">장예서</span>
                  </TableCell>
                  <TableCell className="font-medium">yesyes</TableCell>
                  <TableCell className="hidden md:table-cell">01057362859</TableCell>
                  <TableCell className="hidden md:table-cell">
                    <Switch className="mx-auto" />
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </main>
      </div>
    </div>
  )
}